#!/usr/bin/env bash
# Remediation script generated by remedify for prod-web-host (Ubuntu 22.04) (ubuntu 22.04)
# Review before running. Run as root or with sudo.
set -euo pipefail

apt-get update

# libc6 2.35-0ubuntu3.6 -> 2.35-0ubuntu3.8 [CRITICAL] CVE-2024-33599
#   NOTE: Ubuntu vendor backport — version differs from upstream
#   WARNING: libc update: reboot strongly recommended (all processes link against it).
apt-get install --only-upgrade libc6=2.35-0ubuntu3.8

# libssl3 3.0.2-0ubuntu1.15 -> 3.0.2-0ubuntu1.18 [HIGH] CVE-2024-5535, CVE-2024-6119
#   NOTE: Ubuntu vendor backport — version differs from upstream
#   WARNING: Restart services that link against OpenSSL (nginx, sshd, etc.).
apt-get install --only-upgrade libssl3=3.0.2-0ubuntu1.18

# linux-image-generic 5.15.0.105.102 -> 5.15.0.107.104 [HIGH] CVE-2024-26923
#   WARNING: Kernel update: reboot required.
apt-get install --only-upgrade linux-image-generic=5.15.0.107.104

# curl 7.81.0-1ubuntu1.15 -> 7.81.0-1ubuntu1.16 [MEDIUM] CVE-2024-2398
#   NOTE: Ubuntu vendor backport — version differs from upstream
apt-get install --only-upgrade curl=7.81.0-1ubuntu1.16

echo "One or more updates require a reboot. Schedule one."
