#!/usr/bin/env bash
# Remediation script generated by remedify v0.2.0 for testdata/fixtures/images/ubuntu-1804.tar.gz (ubuntu 18.04)
# Review before running. Run as root or with sudo.
set -euo pipefail

# EOL WARNING: Ubuntu 18.04 standard repositories no longer receive security updates. Fixes for many CVEs require Ubuntu Pro (ESM). Commands below may fail to find the fixed version without ESM enrollment.

apt-get update

# e2fsprogs, libcom-err2, libext2fs2, libss2 1.44.1-1ubuntu1.1 -> 1.44.1-1ubuntu1.2 [MEDIUM] CVE-2019-5094
#   NOTE: Ubuntu vendor backport — version differs from upstream
apt-get install --only-upgrade e2fsprogs=1.44.1-1ubuntu1.2 libcom-err2=1.44.1-1ubuntu1.2 libext2fs2=1.44.1-1ubuntu1.2 libss2=1.44.1-1ubuntu1.2

# --- No fix available (informational) ---
# bash [LOW] CVE-2019-18276: No vendor fix released yet

